#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
  echo -e "Bad arguments \n"
  echo "Usage:"
  echo -e "\tgit_pull_all <root_git_dir>"
  echo "Example:"
  echo -e "\tgit_pull_all ~/GitHub"
  exit 1
fi

for d in $(find $1 -maxdepth 2 -name ".git" -type d)
do
  repo_name=$(echo $d/ | rev | cut -d'/' -f2 --complement | rev)
  echo "$repo_name"
  git -C "$repo_name" pull
done

